#!/bin/bash

set -e -u

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

tmpdir=${tmpdir:-/tmp}
payload="$(mktemp "${tmpdir}/git-release-tags.XXXXXX")"
cat > "${payload}" <&0

destination=$1
if [ -z "${destination}" ]
then
  echo "usage: $0 </path/to/destination>" >&2
  exit 1
fi

# From payload
api_token=$( jq -r '.source.token // ""' < ${payload})
github_repo=$( jq -r '.source.repo // ""' < ${payload})
github_owner=$( jq -r '.source.owner // ""' < ${payload})
release_name=$( jq -r '.source.tag_prefix // ""' < ${payload})
release_version=$( jq -r '.version.version // "latest"' < ${payload})
version="$(jq -r '.version // ""' < "${payload}")"
tag_name=$release_name$release_version

file_url="https://api.github.com/repos/${github_owner}/${github_repo}/tarball/${tag_name}?access_token=$api_token"

mkdir -p "${destination}"
curl -L "${file_url}" > "${destination}/source.tar.gz"
echo "${file_url}" > "${destination}/url"
echo "${release_version}" > "${destination}/version"

jq -n "{
  version: ${version}
}" >&3
